title: baseline
datafile: proj_bnbinge/BNPalmPilotMasterDataFinal.csv
version: 3.1

comment: "bnbinge_gfci_lag"

# name of analysis
aname: ''  #

# # name of data directory
# datadir: data_gfci
# rawdatadir: data
# newlavdir: newlav

# directories to create
directories:
  # name of data directory
  datadir: data
  rawdatadir: data_raw
  data_gfci: data_gfci
  data_gfci_raw: data_gfci_raw
  newlavdir: newlav

steps_global:

  - 
    op: sort
    arg:
      - datetime

  -
    op: recode 
    arg: 
      binge: 
        T: 1.0
        F: 0.0
        nan: 0.0

      vomit: 
        T: 1.0
        F: 0.0
        nan: 0.0
    
      laxative: 
        T: 1.0
        F: 0.0
        nan: 0.0

      exercise: 
        T: 1.0
        F: 0.0
        nan: 0.0

  -
    op: keep
    arg:
      - id
      #- LPAClus
      #- Date
      #- Time
      - datetime
      #- First
      #- CumHrs
      # - Day
      #- EDDAY
      #- EDNOW
      #- EDPRE
      #- EDTIME
      #- SDDAY
      #- SDNOW
      #- SDPRE
      #- SDTIME
      #- Rate
      # - BeepNum
      #- BeepTime
      #- Responsetime
      #- Response_YN
      #- random
      #- event
      #- endofday
      #- attkills
      #- afraid
      # - happy
      #- pomsange
      #- alert
      #- irritabl
      #- proud
      #- ashamed
      #- cheerful
      #- disguste
      #- enthusti
      #- nervous
      #- pomspeev
      #- confiden
      #- jittery
      #- pomsbadt
      #- concentr
      #- sad
      #- energeti
      #- calm
      #- strong
      #- distress
      #- trueself
      #- angryslf
      #- attentiv
      #- lonely
      #- relaxed
      #- whoiam
      #- determin
      # behaviors
      - binge
      - vomit
      #- laxative
      #- exercise
      - PANASNEG
      - PANASPOS
      - POMSAH

  #- 
  #  op: rename
  #  arg: 

  -
    op: save
    arg: 
      dir: data_gfci_raw
      stub: _all.csv

# step for individual case
steps_case:

  -
    op: drop
    arg:
      - id
      #- LPAClus
      - datetime
      #- First
      #- CumHrs

  -
    op: rename
    arg:
      PANASNEG: panasneg
      PANASPOS: panaspos
      POMSAH: pomsah  

  - 
    op: missing_value
    arg: drop

  -
    op: save
    arg: 
      dir: data_raw
      stub: _raw.csv
  -
    op: add_lag
    arg:

  -
    op: save
    arg: 
      dir: data_raw
      stub: _lagged.csv
  
  -
    op: standardize
    arg:
  
  -
    op: save
    arg: 
      dir: data
      stub: .csv 

variables:

  # minimum number of raw rows
  min_raw_rows: 60

# src and des after renaming
  src: 
    - N_afraid
    - N_ashamed
    - N_distress
    - N_irritabl
    - N_jittery    
    - N_nervous
    - P_alert
    - P_attentiv
    - P_determin 
    - P_enthusti
    - P_proud
    - P_strong

          
  des:  [binge]

effectsize:
  binge: # the des
  # src 
    src:  
      - panasneg
      - panasneg_lag
      - panaspos
      - panaspos_lag
      - pomsah
      - pomsah_lag

  vomit: # the des
  # src
    src:  
      - panasneg
      - panasneg_lag
      - panaspos
      - panaspos_lag
      - pomsah
      - pomsah_lag
      


causal-cmd:
  alpha: 0.05
  algorithm: gfci
  dataset: 
  data-type: continuous
  delimiter: comma
  json-graph: False
  knowledge: prior.txt
  out: output_gfci
  penaltyDiscount: 1.0
  prefix:
  score: sem-bic-score
  skip-latest: True
  test: fisher-z-test
  thread: 1
  version: 1.2.2
  cmdpath: ~/bin

plotting:
  plot_all_edges: True   # default is False
  fontname: Helvetica
  label_edge_types: [-->, o-> , o-o ]
  min_pvalue: 1
  show_pvalue: True

# type of edges to include in model
include_model_edges: [ ['-->','~'], ['o->','~']  ]


check:
  # condition - to not include 'all_cases'
  condition: "id != 'all_cases'"

  # this is the list of edges to check and then provide the total
  edges:
    # panasneg
    panasneg1: [panasneg, -->, binge]
    panasneg2: [panasneg_lag, -->, binge ]
    panasneg3: [panasneg, o->, binge]
    panasneg4: [panasneg, o-o, binge ]
    panasneg5: [binge, o-o, panasneg]
    panasneg6: [panasneg, <->, binge ]
    panasneg7: [binge, <->, panasneg ]

    # panaspos
    panaspos1: [panaspos, -->, binge]
    panaspos2: [panaspos_lag, -->, binge]
    panaspos3: [panaspos, o->, binge]
    panaspos5: [panaspos, o-o, binge ]
    panaspos4: [binge, o-o, panaspos]
    panaspos5: [panaspos, <->, binge ]
    panaspos4: [binge, <->, panaspos ]

    # pomsah
    pomsah1: [pomsah, -->, binge]
    pomsah2: [pomsah_lag, -->, binge]
    pomsah3: [pomsah, o->, binge]
    pomsah4: [pomsah, o-o, binge ]
    pomsah5: [binge, o-o, pomsah ]
    pomsah6: [pomsah, <->, binge ]
    pomsah7: [binge, <->, pomsah ]

    # vomit
    vomit1: [vomit, -->, binge]
    vomit2: [vomit_lag, -->, binge]
    vomit3: [vomit, o->, binge]
    vomit4: [vomit, o-o, binge]  
    vomit5: [binge, o-o, vomit]  
    vomit6: [vomit, <->, binge]  
    vomit7: [binge, <->, vomit]  

    # binge
    binge1: [binge, -->, vomit]
    binge2: [binge_lag, -->, vomit]
    binge3: [binge, o->, vomit]
    binge4: [binge, o-o, vomit]
    binge5: [vomit, o-o, binge]
    binge6: [binge, <->, vomit]
    binge7: [vomit, <->, binge]

# causal paths summary pairs to check
causal_path_pairs:
  pair1: [panasneg, binge]
  pair2: [panaspos, binge]
